name: lint
on:
    push:
        branches:
        - main
    pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: npm i --frozen-lockfile

      - name: Prettier
        run: npm run prettier-check
